FROM eclipse-temurin:17

LABEL mentainer="aakashmishraam5@gmail.com"

WORKDIR /app

COPY target/Spring-boot-Blog-REST-API-0.0.1-SNAPSHOT.jar /app/springboot-blog.jar

ENTRYPOINT ["java","-jar","springboot-blog.jar"]